### ISSUE TITLE
Make sure tooltip is readable

### ISSUE THREAD

**Issue by john-guerra** [john-guerra/navio#19]
You can't read the tooltip when hovering over the last items. 

I think we should change the tooltip to be an html element, and therefore have more control on how it shows

**Comment by jgmurillo10** [comment]
Also, take into account x position because on large text, reading items difficult or impossible. 
![image](https://user-images.githubusercontent.com/16781872/54562165-6e897380-4994-11e9-8d00-2c97b026fd28.png)
