### ISSUE TITLE
Use transition when changing data

### ISSUE THREAD

**Issue by kaustavbhattacharjee** [john-guerra/navio#45]
I have a situation where I need to perform the following steps:
- Step 1: Load navio with data1
- Step 2: Again load navio with data2

I would like to slow down the transition between these steps. Does Navio provide any function where you can reload the data and specify the transition duration (like in d3.js)?

**Comment by john-guerra** [comment]
Hi, unfortunately transitions wouldn't be possible as I use canvas for drawing the records. Because of that the traditional transitions from D3 wouldn't apply
