### ISSUE TITLE
change the date parsing format

### ISSUE THREAD

**Issue by john-guerra** [john-guerra/navio#8]

**Comment by john-guerra** [comment]
It would be nice to support dates as a different data type

**Comment by jgmurillo10** [comment]
It will be required d3.time to help parsing the date. The expected behaviour will be something like:

```js
navio.addDateAttrib([name], "%Y%m%d");
```

And underneath use
`var parser = d3.timeParse("%Y%m%d");`

**Comment by john-guerra** [comment]
I would rather have it such that the user has to parse the date themselves
